# Autogenerated wrapper script for Gnuplot_jll for aarch64-linux-musl
export gnuplot

using libwebp_jll
using Libcerf_jll
using LibGD_jll
using Cairo_jll
using Pango_jll
using Libffi_jll
using Libiconv_jll
using Readline_jll
using Qt5Svg_jll
JLLWrappers.@generate_wrapper_header("Gnuplot")
JLLWrappers.@declare_executable_product(gnuplot)
function __init__()
    JLLWrappers.@generate_init_header(libwebp_jll, Libcerf_jll, LibGD_jll, Cairo_jll, Pango_jll, Libffi_jll, Libiconv_jll, Readline_jll, Qt5Svg_jll)
    JLLWrappers.@init_executable_product(
        gnuplot,
        "bin/gnuplot",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
